-- Tables
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  classes TEXT[] NOT NULL
);

CREATE TABLE individuals (
  id UUID PRIMARY KEY DEFAULT uuidv4(),
  email TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS individual_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_id UUID NOT NULL,
  manufacturer TEXT NOT NULL,
  model TEXT NOT NULL,
  CONSTRAINT fk_individual_devices_individuals FOREIGN KEY (individual_id) REFERENCES individuals(id)
);

CREATE TABLE IF NOT EXISTS individual_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL,
  unit TEXT NOT NULL,
  device_id BIGINT NOT NULL,
  CONSTRAINT fk_individual_categories_categories FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT fk_individual_categories_individual_devices FOREIGN KEY (device_id) REFERENCES individual_devices(id)
);

CREATE TABLE IF NOT EXISTS datastreams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_category_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  CONSTRAINT fk_datastreams_individual_categories FOREIGN KEY (individual_category_id) REFERENCES individual_categories(id)
);

-- Indices
CREATE INDEX IF NOT EXISTS idx_individual_devices_individual_id ON individual_devices(individual_id);

CREATE INDEX IF NOT EXISTS idx_individual_categories_category_id ON individual_categories(category_id);
CREATE INDEX IF NOT EXISTS idx_individual_categories_device_id ON individual_categories(device_id);

CREATE INDEX IF NOT EXISTS idx_datastreams_individual_category_id ON datastreams(individual_category_id);

-- Views
DROP VIEW IF EXISTS datastream_overview;
CREATE VIEW datastream_overview AS
	SELECT DISTINCT ON (icat.id) icat.id, ds.created_at, ds.value, cat.id AS category_id, cat.description AS category_description, cat.classes, icat.unit,  idev.individual_id, idev.manufacturer, idev.model
	FROM datastreams ds
	LEFT JOIN individual_categories icat ON ds.individual_category_id = icat.id
	LEFT JOIN categories cat ON icat.category_id = cat.id
	LEFT JOIN individual_devices idev ON icat.device_id = idev.id
	ORDER BY icat.id, ds.created_at DESC;
