-- Extensions
CREATE EXTENSION plpython3u;

-- Tables
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  classes TEXT[] NOT NULL
);

CREATE TABLE individuals (
  id UUID PRIMARY KEY DEFAULT uuidv4(),
  email TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS individual_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_id UUID NOT NULL,
  manufacturer TEXT NOT NULL,
  model TEXT NOT NULL,
  CONSTRAINT fk_individual_devices_individuals FOREIGN KEY (individual_id) REFERENCES individuals(id)
);

CREATE TABLE IF NOT EXISTS individual_categories (
  id UUID PRIMARY KEY DEFAULT uuidv4(),
  category_id BIGINT NOT NULL,
  unit TEXT NOT NULL,
  device_id BIGINT NOT NULL,
  CONSTRAINT fk_individual_categories_categories FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT fk_individual_categories_individual_devices FOREIGN KEY (device_id) REFERENCES individual_devices(id)
);

CREATE TABLE IF NOT EXISTS datastreams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_category_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  CONSTRAINT fk_datastreams_individual_categories FOREIGN KEY (individual_category_id) REFERENCES individual_categories(id)
);

-- Indices
CREATE INDEX IF NOT EXISTS idx_individual_devices_individual_id ON individual_devices(individual_id);

CREATE INDEX IF NOT EXISTS idx_individual_categories_category_id ON individual_categories(category_id);
CREATE INDEX IF NOT EXISTS idx_individual_categories_device_id ON individual_categories(device_id);

CREATE INDEX IF NOT EXISTS idx_datastreams_individual_category_id ON datastreams(individual_category_id);


-- Functions
CREATE OR REPLACE FUNCTION last_single_day(page int, p_individual_id UUID, p_category_id BIGINT)
RETURNS TABLE (
    instant TIMESTAMPTZ, value numeric
)
LANGUAGE plpgsql
AS $$
DECLARE
    lower_bound TIMESTAMPTZ;
    upper_bound TIMESTAMPTZ;
BEGIN
    lower_bound := CURRENT_DATE - (page * INTERVAL '1 day');
    upper_bound := CURRENT_DATE - (page * INTERVAL '1 day') + INTERVAL '1 day';

  RETURN QUERY
	SELECT
		ds.created_at AS instant,
		ROUND(ds.value::numeric, 2)
	FROM datastreams ds
	LEFT JOIN individual_categories icat ON ds.individual_category_id = icat.id
	LEFT JOIN individual_devices idev ON icat.device_id = idev.id
	WHERE ds.created_at >= lower_bound
		AND ds.created_at < upper_bound
		AND idev.individual_id = p_individual_id
		AND icat.category_id = p_category_id
	ORDER BY instant DESC;
END;
$$;

CREATE OR REPLACE FUNCTION last_n_days(window_size varchar(1), page int, p_individual_id UUID, p_category_id BIGINT)
RETURNS TABLE (
    instant TIMESTAMPTZ, avg numeric, sum numeric, min numeric, max numeric
)
LANGUAGE plpgsql
AS $$
DECLARE
    lower_bound TIMESTAMPTZ;
    upper_bound TIMESTAMPTZ;
BEGIN
    lower_bound := CASE window_size
        WHEN 'y' THEN CURRENT_DATE - (page * INTERVAL '1 year') - INTERVAL '1 year - 1 day'
        WHEN 'm' THEN CURRENT_DATE - (page * INTERVAL '4 week') - INTERVAL '3 weeks 6 days'
        ELSE CURRENT_DATE - (page * INTERVAL '1 week') - INTERVAL '6 days'
    END CASE;

    upper_bound := CASE window_size
        WHEN 'y' THEN CURRENT_DATE - (page * INTERVAL '1 year') + INTERVAL '1 day'
        WHEN 'm' THEN CURRENT_DATE - (page * INTERVAL '4 week') + INTERVAL '1 day'
        ELSE CURRENT_DATE - (page * INTERVAL '1 week') + INTERVAL '1 day'
    END CASE;

  RETURN QUERY
	SELECT
		date_trunc('day', ds.created_at) AS instant,
		ROUND(AVG(ds.value)::numeric, 2),
		ROUND(SUM(ds.value)::numeric, 2),
		ROUND(MIN(ds.value)::numeric, 2),
		ROUND(MAX(ds.value)::numeric, 2)
	FROM datastreams ds
	LEFT JOIN individual_categories icat ON ds.individual_category_id = icat.id
	LEFT JOIN individual_devices idev ON icat.device_id = idev.id
	WHERE ds.created_at >= lower_bound
		AND ds.created_at  < upper_bound
		AND idev.individual_id = p_individual_id
		AND icat.category_id = p_category_id
	GROUP BY instant
	ORDER BY instant DESC;
END;
$$;

CREATE OR REPLACE FUNCTION last_twelve_months(page int, p_individual_id UUID, p_category_id BIGINT)
RETURNS TABLE (
    instant TIMESTAMPTZ, avg numeric, sum numeric, min numeric, max numeric
)
LANGUAGE plpgsql
AS $$
DECLARE
    lower_bound TIMESTAMPTZ;
    upper_bound TIMESTAMPTZ;
BEGIN
    lower_bound := date_trunc('month', CURRENT_DATE) - (page * INTERVAL '1 year') - INTERVAL '11 months';
    upper_bound := date_trunc('month', CURRENT_DATE) - (page * INTERVAL '1 year') + INTERVAL '1 month';

  RETURN QUERY
	SELECT
		date_trunc('month', ds.instant) AS instant,
		ROUND(AVG(ds.avg), 2),
		ROUND(AVG(ds.sum), 2),
		ROUND(AVG(ds.min), 2),
		ROUND(AVG(ds.max), 2)
	FROM last_n_days('y', page, p_individual_id, p_category_id) AS ds
	WHERE ds.instant >= lower_bound
		AND ds.instant  < upper_bound
	GROUP BY date_trunc('month', ds.instant)
	ORDER BY date_trunc('month', ds.instant) DESC;
END;
$$;

-- Views
DROP VIEW IF EXISTS datastream_overview;
CREATE VIEW datastream_overview AS
	SELECT DISTINCT ON (icat.id) icat.id, ds.created_at, ds.value, cat.id AS category_id, cat.description AS category_description, cat.classes, icat.unit,  idev.individual_id, idev.manufacturer, idev.model
	FROM datastreams ds
	LEFT JOIN individual_categories icat ON ds.individual_category_id = icat.id
	LEFT JOIN categories cat ON icat.category_id = cat.id
	LEFT JOIN individual_devices idev ON icat.device_id = idev.id
	ORDER BY icat.id, ds.created_at DESC;
