-- Needed for UUIDv4
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- Tables
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL
);

CREATE TABLE individuals (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS individual_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_id UUID NOT NULL,
  manufacturer TEXT NOT NULL,
  model TEXT NOT NULL,
  CONSTRAINT fk_individual_devices_individuals FOREIGN KEY (individual_id) REFERENCES individuals(id)
);

CREATE TABLE IF NOT EXISTS individual_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL,
  unit TEXT NOT NULL,
  device_id BIGINT NOT NULL,
  CONSTRAINT fk_individual_categories_categories FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT fk_individual_categories_individual_devices FOREIGN KEY (device_id) REFERENCES individual_devices(id)
);

CREATE TABLE IF NOT EXISTS datastreams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_category_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  CONSTRAINT fk_datastreams_individual_categories FOREIGN KEY (individual_category_id) REFERENCES individual_categories(id)
);

-- Indices
CREATE INDEX IF NOT EXISTS idx_individual_devices_individual_id ON individual_devices(individual_id);

CREATE INDEX IF NOT EXISTS idx_individual_categories_category_id ON individual_categories(category_id);
CREATE INDEX IF NOT EXISTS idx_individual_categories_device_id ON individual_categories(device_id);

CREATE INDEX IF NOT EXISTS idx_datastreams_individual_category_id ON datastreams(individual_category_id);
